"""Seed data definitions for Curriculum and Skill Graph (Backend SDE2 focus)."""

from typing import Any

SEEDED_SKILLS: list[dict[str, Any]] = [
    {
        "id": "sql_fundamentals",
        "slug": "sql-fundamentals",
        "name": "SQL Fundamentals & Relational Modeling",
        "description": "Understanding relational algebra, normalization, query parsing, and relational execution models.",
        "category": "Database",
    },
    {
        "id": "database_indexing",
        "slug": "database-indexing",
        "name": "Database Indexing & Query Optimization",
        "description": "B+Tree structures, clustered vs non-clustered indexes, composite indexing, selectivity, and EXPLAIN plan analysis.",
        "category": "Database",
    },
    {
        "id": "transactions",
        "slug": "transactions-concurrency",
        "name": "Transactions & Concurrency Control",
        "description": "ACID properties, isolation levels, write-ahead logging (WAL), multi-version concurrency control (MVCC), and deadlocks.",
        "category": "Database",
    },
    {
        "id": "caching",
        "slug": "caching-patterns",
        "name": "Caching Strategies & Distributed Caching",
        "description": "Cache-aside, write-through/behind patterns, TTL invalidation, cache stampede mitigation, and eviction algorithms.",
        "category": "Distributed Systems",
    },
    {
        "id": "distributed_systems",
        "slug": "distributed-systems-fundamentals",
        "name": "Distributed Systems Fundamentals",
        "description": "CAP theorem, PACELC, network partitions, replication models, consensus mechanisms, and fault tolerance.",
        "category": "Distributed Systems",
    },
    {
        "id": "messaging_queues",
        "slug": "messaging-queues",
        "name": "Messaging, Queues & Event Streaming",
        "description": "Point-to-point queues, pub/sub fanout, backpressure, idempotency, dead letter queues (DLQ), and event-driven semantics.",
        "category": "Distributed Systems",
    },
    {
        "id": "system_design",
        "slug": "system-design-fundamentals",
        "name": "System Design & High-Scalability Architecture",
        "description": "End-to-end architectural trade-offs, high availability, rate limiting, data partitioning, and throughput scaling.",
        "category": "System Design",
    },
]

SEEDED_TOPICS: list[dict[str, Any]] = [
    {
        "id": "topic_sql_execution",
        "slug": "sql-query-execution-fundamentals",
        "title": "SQL Query Execution & Fundamentals",
        "description": "How relational database engines parse, optimize, plan, and execute SQL statements across storage engines.",
        "skill_id": "sql_fundamentals",
        "target_mastery": 0.85,
        "importance_weight": 4.0,
        "order_index": 1,
        "prerequisites": [],
        "resource": {
            "id": "res_sql_execution",
            "resource_type": "youtube",
            "title": "How Relational Databases Execute Queries Internally",
            "url": "https://www.youtube.com/watch?v=0k5G6F04bJk",
            "author": "CMU Database Group",
            "duration_seconds": 3600,
            "transcript_status": "available",
            "summary": "Deep dive into SQL query parsing, binding, relational algebra expressions, logical plan optimization, and physical plan generation.",
            "metadata_json": {
                "level": "Intermediate",
                "key_takeaways": [
                    "Query lifecycle: Parser -> Rewriter -> Planner -> Executor",
                    "Cost-based vs Rule-based query optimizers",
                    "Sequential scans vs index scans",
                ],
            },
        },
    },
    {
        "id": "topic_db_indexing",
        "slug": "database-indexing-b-trees",
        "title": "Database Indexing & B-Trees",
        "description": "Internal mechanics of B+ Trees, clustered vs secondary indexes, composite index prefix rules, and query optimization trade-offs.",
        "skill_id": "database_indexing",
        "target_mastery": 0.85,
        "importance_weight": 5.0,
        "order_index": 2,
        "prerequisites": ["topic_sql_execution"],
        "resource": {
            "id": "res_db_indexing",
            "resource_type": "youtube",
            "title": "Database Indexing Explained: B-Trees and Composite Indexes",
            "url": "https://www.youtube.com/watch?v=-qNSXK7s7_w",
            "author": "Hussein Nasser",
            "duration_seconds": 2400,
            "transcript_status": "available",
            "summary": "Comprehensive explanation of B+ Tree data structure in relational databases, clustered primary indexes, secondary index pointer lookups, index selectivity, and write amplification costs.",
            "metadata_json": {
                "level": "Advanced",
                "key_takeaways": [
                    "B+ Tree branch nodes vs leaf nodes with sequential pointers",
                    "Leftmost prefix rule for composite indexes (colA, colB)",
                    "Covering indexes eliminating table heap lookups",
                    "Write amplification penalty on INSERT/UPDATE/DELETE",
                ],
            },
        },
    },
    {
        "id": "topic_transactions_acid",
        "slug": "database-transactions-acid",
        "title": "Database Transactions & ACID Guarantees",
        "description": "Understanding Atomicity, Consistency, Isolation, Durability, Write-Ahead Logging (WAL), and crash recovery.",
        "skill_id": "transactions",
        "target_mastery": 0.80,
        "importance_weight": 4.5,
        "order_index": 3,
        "prerequisites": ["topic_sql_execution"],
        "resource": {
            "id": "res_transactions_acid",
            "resource_type": "youtube",
            "title": "ACID Properties & Write-Ahead Logging (WAL) Architecture",
            "url": "https://www.youtube.com/watch?v=5ZjhNTM8XU8",
            "author": "ByteByteGo",
            "duration_seconds": 1800,
            "transcript_status": "available",
            "summary": "How ACID guarantees are upheld under hardware crashes using write-ahead logs, dirty buffer flushes, and ARIES recovery protocols.",
            "metadata_json": {
                "level": "Intermediate",
                "key_takeaways": [
                    "Atomicity through undo logs",
                    "Durability through redo logs and WAL append-only writes",
                    "Flush before commit invariants",
                ],
            },
        },
    },
    {
        "id": "topic_isolation_concurrency",
        "slug": "isolation-levels-concurrency",
        "title": "Concurrency Control & Isolation Levels",
        "description": "Phenomena including dirty reads, non-repeatable reads, phantom reads, serialization anomalies, and Multi-Version Concurrency Control (MVCC).",
        "skill_id": "transactions",
        "target_mastery": 0.80,
        "importance_weight": 4.8,
        "order_index": 4,
        "prerequisites": ["topic_transactions_acid"],
        "resource": {
            "id": "res_isolation_concurrency",
            "resource_type": "youtube",
            "title": "Database Isolation Levels & MVCC Deep Dive",
            "url": "https://www.youtube.com/watch?v=4EajrWtST0U",
            "author": "Hussein Nasser",
            "duration_seconds": 2700,
            "transcript_status": "available",
            "summary": "Detailed exploration of SQL ANSI isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable) and how MVCC avoids read/write locking contention.",
            "metadata_json": {
                "level": "Advanced",
                "key_takeaways": [
                    "Dirty reads vs fuzzy reads vs phantom reads",
                    "Snapshot isolation and write-skew anomalies",
                    "Postgres and MySQL MVCC snapshot implementations (xmin, xmax, undo log chains)",
                ],
            },
        },
    },
    {
        "id": "topic_caching_strategies",
        "slug": "caching-strategies-invalidation",
        "title": "Caching Strategies & Invalidation",
        "description": "Cache-aside, write-through, write-behind patterns, cache stampede (thundering herd), TTL jitter, and eviction policies.",
        "skill_id": "caching",
        "target_mastery": 0.80,
        "importance_weight": 4.2,
        "order_index": 5,
        "prerequisites": ["topic_sql_execution"],
        "resource": {
            "id": "res_caching_strategies",
            "resource_type": "youtube",
            "title": "Caching Patterns and Cache Invalidation at Scale",
            "url": "https://www.youtube.com/watch?v=U3RkDLtS7uY",
            "author": "ByteByteGo",
            "duration_seconds": 1500,
            "transcript_status": "available",
            "summary": "Architecture of distributed in-memory caches (Redis/Memcached), cache eviction algorithms (LRU, LFU, ARC), and cache stampede solutions.",
            "metadata_json": {
                "level": "Intermediate",
                "key_takeaways": [
                    "Cache-aside vs Write-through consistency guarantees",
                    "Distributed locks and probabilistic early expiration (XFetch) for cache stampedes",
                    "Dual-write consistency challenges and out-of-order updates",
                ],
            },
        },
    },
    {
        "id": "topic_distributed_systems_cap",
        "slug": "distributed-systems-cap-theorem",
        "title": "Distributed Systems Fundamentals & CAP Theorem",
        "description": "Network partitions, trade-offs between linearizability and availability, PACELC theorem, and quorum replication models.",
        "skill_id": "distributed_systems",
        "target_mastery": 0.80,
        "importance_weight": 4.7,
        "order_index": 6,
        "prerequisites": ["topic_caching_strategies"],
        "resource": {
            "id": "res_distributed_systems_cap",
            "resource_type": "youtube",
            "title": "Distributed Systems & The CAP Theorem in Practice",
            "url": "https://www.youtube.com/watch?v=k-Yaq8AHlFA",
            "author": "Martin Kleppmann",
            "duration_seconds": 3200,
            "transcript_status": "available",
            "summary": "Fundamental properties of distributed state machines: synchronous vs asynchronous networks, unreliability of clocks, CAP theorem formalization, and quorum replication (R+W > N).",
            "metadata_json": {
                "level": "Advanced",
                "key_takeaways": [
                    "Why partition tolerance is mandatory over real networks",
                    "Strong consistency (Linearizability) vs Eventual consistency",
                    "Leader-follower vs multi-leader vs leaderless quorum replication",
                ],
            },
        },
    },
    {
        "id": "topic_message_queues",
        "slug": "message-queues-asynchronous-processing",
        "title": "Message Queues & Asynchronous Processing",
        "description": "Decoupling synchronous workloads, producer-consumer architectures, queue backpressure, Dead Letter Queues (DLQ), and consumer scaling.",
        "skill_id": "messaging_queues",
        "target_mastery": 0.80,
        "importance_weight": 4.5,
        "order_index": 7,
        "prerequisites": ["topic_distributed_systems_cap"],
        "resource": {
            "id": "res_message_queues",
            "resource_type": "youtube",
            "title": "Message Queues vs Event Streams (RabbitMQ vs Kafka)",
            "url": "https://www.youtube.com/watch?v=oUJbuFMyBDk",
            "author": "ByteByteGo",
            "duration_seconds": 1900,
            "transcript_status": "available",
            "summary": "Key differences between ephemeral message brokers (RabbitMQ/SQS) and distributed append-only commit logs (Kafka/Pulsar), consumer groups, and ordering guarantees.",
            "metadata_json": {
                "level": "Intermediate",
                "key_takeaways": [
                    "Push vs Pull delivery models",
                    "Dead Letter Queues, exponential backoff, and poison pill handling",
                    "Partition-level ordering vs global ordering",
                ],
            },
        },
    },
    {
        "id": "topic_event_driven_arch",
        "slug": "event-driven-architecture-pubsub",
        "title": "Event-Driven Architecture & Pub/Sub Patterns",
        "description": "Event notification vs event-carried state transfer, pub/sub fanout, transactional outbox pattern, and idempotent consumer design.",
        "skill_id": "messaging_queues",
        "target_mastery": 0.75,
        "importance_weight": 4.3,
        "order_index": 8,
        "prerequisites": ["topic_message_queues"],
        "resource": {
            "id": "res_event_driven_arch",
            "resource_type": "youtube",
            "title": "Event-Driven Architecture & The Transactional Outbox Pattern",
            "url": "https://www.youtube.com/watch?v=F3vA_E10q_E",
            "author": "CodeOpinion",
            "duration_seconds": 2100,
            "transcript_status": "available",
            "summary": "Reliable event publishing across database and message broker boundaries using Transactional Outbox and Change Data Capture (CDC) with Debezium.",
            "metadata_json": {
                "level": "Advanced",
                "key_takeaways": [
                    "Dual-write vulnerability: DB write succeeding while message broker fails",
                    "Transactional Outbox pattern ensuring at-least-once delivery",
                    "Consumer idempotency using unique deduplication keys",
                ],
            },
        },
    },
    {
        "id": "topic_distributed_transactions",
        "slug": "distributed-transactions-saga-pattern",
        "title": "Distributed Transactions & The Saga Pattern",
        "description": "Two-Phase Commit (2PC) failure modes, Saga choreography vs orchestration, compensating transactions, and forward/backward recovery.",
        "skill_id": "distributed_systems",
        "target_mastery": 0.75,
        "importance_weight": 4.6,
        "order_index": 9,
        "prerequisites": ["topic_transactions_acid", "topic_event_driven_arch"],
        "resource": {
            "id": "res_distributed_transactions",
            "resource_type": "youtube",
            "title": "Distributed Transactions: 2PC vs Saga Pattern Explained",
            "url": "https://www.youtube.com/watch?v=0UTOLRTwOX0",
            "author": "ByteByteGo",
            "duration_seconds": 2200,
            "transcript_status": "available",
            "summary": "Why 2PC creates blocking locks across services and how Saga patterns manage distributed state transitions via compensating actions.",
            "metadata_json": {
                "level": "Advanced",
                "key_takeaways": [
                    "2PC coordinator failure and blocking locking states",
                    "Saga Orchestrator state machine vs Choreography event storms",
                    "Compensating transaction design for non-reversible operations",
                ],
            },
        },
    },
    {
        "id": "topic_system_design_orders",
        "slug": "scalable-order-processing-system-design",
        "title": "System Design: Scalable Order Processing Engine",
        "description": "End-to-end architecture design for a high-concurrency order placement and inventory reservation system under flash-sale load.",
        "skill_id": "system_design",
        "target_mastery": 0.85,
        "importance_weight": 5.0,
        "order_index": 10,
        "prerequisites": [
            "topic_db_indexing",
            "topic_message_queues",
            "topic_distributed_transactions",
        ],
        "resource": {
            "id": "res_system_design_orders",
            "resource_type": "youtube",
            "title": "System Design Interview: High-Throughput Order Management System",
            "url": "https://www.youtube.com/watch?v=gA_hYm5l4R8",
            "author": "Jordan Has No Life",
            "duration_seconds": 3500,
            "transcript_status": "available",
            "summary": "Comprehensive architecture walkthrough: inventory decrement with Redis Lua scripts, asynchronous order creation via message streams, database sharding by order_id/user_id, and payment webhook idempotency.",
            "metadata_json": {
                "level": "Expert",
                "key_takeaways": [
                    "Atomic inventory pre-allocation using Redis Lua scripts",
                    "Asynchronous fulfillment pipeline with DLQ and reconciliation jobs",
                    "Idempotent payment capture and event-driven status transitions",
                    "Handling database hot-spots during flash sales",
                ],
            },
        },
    },
]
